# Generated by Django 3.1.7 on 2021-04-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_added_fields_to_userprofile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_user_image.png', upload_to='users/profile_pics'),
        ),
    ]
