# Generated by Django 3.1.7 on 2021-04-05 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210405_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 5)),
            preserve_default=False,
        ),
    ]
