# Generated by Django 3.1.7 on 2021-04-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_create_orderstatus_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.orderstatus', verbose_name='Order status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.paymenttype', verbose_name='Order payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shippingtype', verbose_name='Order shipping type'),
        ),
    ]
