# Generated by Django 3.1.7 on 2021-04-05 06:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_updated_fields_for_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_shipping',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 5, 13, 26, 3, 937680)),
            preserve_default=False,
        ),
    ]
