# Generated by Django 3.1.7 on 2021-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210407_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(choices=[(38.0, 38.0), (38.5, 38.5), (39.0, 39.0), (39.5, 39.5), (40.0, 40.0), (40.5, 40.5), (41.0, 41.0), (41.5, 41.5), (42.0, 42.0), (42.5, 42.5), (43.0, 43.0), (43.5, 43.5), (44.0, 44.0), (44.5, 44.5)], default=41.5),
        ),
    ]
